/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/$personId'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedBooksIdRouteImport } from './routes/_authenticated/books/$id'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts/$id'
import { Route as AuthenticatedContactsNewRouteImport } from './routes/_authenticated/contacts/new'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksIdRoute = AuthenticatedBooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsNewRoute =
  AuthenticatedContactsNewRouteImport.update({
    id: '/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$personId': typeof AuthenticatedPersonIdRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/books/$id': typeof AuthenticatedBooksIdRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
}
export interface FileRoutesByTo {
  '/$personId': typeof AuthenticatedPersonIdRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/books/$id': typeof AuthenticatedBooksIdRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/contacts/new': typeof AuthenticatedContactsNewRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/$personId': typeof AuthenticatedPersonIdRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/books/$id': typeof AuthenticatedBooksIdRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/contacts/new': typeof AuthenticatedContactsNewRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$personId'
    | '/invitations'
    | '/profile'
    | '/books/$id'
    | '/contacts/$id'
    | '/contacts/new'
    | '/groups/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$personId'
    | '/invitations'
    | '/profile'
    | '/'
    | '/books/$id'
    | '/contacts/$id'
    | '/contacts/new'
    | '/groups/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$personId'
    | '/_authenticated/invitations'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/books/$id'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/contacts/new'
    | '/_authenticated/groups/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$personId': {
      id: '/_authenticated/$personId'
      path: '/$personId'
      fullPath: '/$personId'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$id': {
      id: '/_authenticated/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof AuthenticatedBooksIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/new': {
      id: '/_authenticated/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthenticatedContactsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBooksIdRoute: typeof AuthenticatedBooksIdRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedContactsNewRoute: typeof AuthenticatedContactsNewRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBooksIdRoute: AuthenticatedBooksIdRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedContactsNewRoute: AuthenticatedContactsNewRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
